cabal-version: 3.14
name: ghc-paths
version: 0.1.0.13
license: BSD-3-Clause
license-file: LICENSE
copyright: (c) Simon Marlow
author: Simon Marlow
maintainer: Simon Marlow <marlowsd@gmail.com>
stability: stable
synopsis: Knowledge of GHC's installation directories
description: Knowledge of GHC's installation directories
category: Development
build-type: Hooks

tested-with:
  GHC == 9.14.1
  GHC == 9.12.2
  GHC == 9.10.2
  GHC == 9.8.4
  GHC == 9.6.7

custom-setup
        setup-depends:
            base        >= 4.18 && < 5
          , Cabal       >= 3.16
          , Cabal-hooks >= 3.16
          , directory
          , process

library
        build-depends: base >= 3 && < 5
        exposed-modules: GHC.Paths
        default-language: Haskell2010

source-repository head
  type:     git
  location: https://github.com/simonmar/ghc-paths
